import type { AuditEvent } from "./types";

/**
 * Mock audit events for local development.
 * No message body content is included — only metadata and protocol state.
 */
export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "evt_001",
    kind: "session.started",
    category: "security",
    ts: "2026-06-16T13:42:00.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Session started",
  },
  {
    id: "evt_002",
    kind: "identity.resolved",
    category: "security",
    ts: "2026-06-16T13:42:05.000Z",
    actor: { type: "system" },
    summary: "Resolved identity for sender marcin@kaizen.io",
    context: { senderAddress: "GBZY...1MNK", senderDisplayName: "Marcin Kowalski" },
  },
  {
    id: "evt_003",
    kind: "policy.default_changed",
    category: "policy",
    ts: "2026-06-16T13:45:18.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Default policy changed to «request approval»",
    context: { policyValue: "request" },
  },
  {
    id: "evt_004",
    kind: "postage.attached",
    category: "billing",
    ts: "2026-06-16T13:50:02.000Z",
    actor: { type: "system" },
    summary: "Postage attached for incoming message",
    context: { messageId: "msg_4f2a", amount: "0.0001", currency: "XLM" },
  },
  {
    id: "evt_005",
    kind: "delivery.message_received",
    category: "delivery",
    ts: "2026-06-16T13:50:04.000Z",
    actor: { type: "relay", relayId: "relay-us-east-1" },
    summary: "Message received from marcin@kaizen.io",
    context: { messageId: "msg_4f2a", senderDisplayName: "Marcin Kowalski" },
  },
  {
    id: "evt_006",
    kind: "policy.sender_allowed",
    category: "policy",
    ts: "2026-06-16T13:52:30.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Sender allowed: Marcin Kowalski",
    context: { senderAddress: "GBZY...1MNK", senderDisplayName: "Marcin Kowalski" },
  },
  {
    id: "evt_007",
    kind: "delivery.receipt_issued",
    category: "delivery",
    ts: "2026-06-16T13:52:35.000Z",
    actor: { type: "system" },
    summary: "Delivery receipt issued for msg_4f2a",
    context: { messageId: "msg_4f2a" },
  },
  {
    id: "evt_008",
    kind: "policy.sender_blocked",
    category: "policy",
    ts: "2026-06-16T14:01:00.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Sender blocked: bulk-promo@offers.biz",
    context: { senderAddress: "GCXX...9QRS", senderDisplayName: "bulk-promo@offers.biz" },
  },
  {
    id: "evt_009",
    kind: "identity.verification_failed",
    category: "security",
    ts: "2026-06-16T14:05:11.000Z",
    actor: { type: "system" },
    summary: "Identity verification failed for unknown sender",
    context: { senderAddress: "GCXX...7LAB" },
  },
  {
    id: "evt_010",
    kind: "delivery.message_bounced",
    category: "delivery",
    ts: "2026-06-16T14:05:13.000Z",
    actor: { type: "relay", relayId: "relay-us-east-1" },
    summary: "Message bounced — sender did not pass policy",
    context: { messageId: "msg_9c8b", senderAddress: "GCXX...7LAB" },
  },
  {
    id: "evt_011",
    kind: "postage.settled",
    category: "billing",
    ts: "2026-06-16T14:10:00.000Z",
    actor: { type: "system" },
    summary: "Postage settled for msg_4f2a",
    context: { messageId: "msg_4f2a", amount: "0.0001", currency: "XLM" },
  },
  {
    id: "evt_012",
    kind: "postage.refunded",
    category: "billing",
    ts: "2026-06-16T14:15:22.000Z",
    actor: { type: "system" },
    summary: "Postage refunded — message rejected by policy",
    context: { messageId: "msg_9c8b", amount: "0.0001", currency: "XLM" },
  },
  {
    id: "evt_013",
    kind: "policy.sender_verified",
    category: "policy",
    ts: "2026-06-16T14:20:44.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Sender set to «verified only»: Priya S.",
    context: { senderAddress: "GDMN...2PLQ", senderDisplayName: "Priya S." },
  },
  {
    id: "evt_014",
    kind: "session.ended",
    category: "security",
    ts: "2026-06-16T14:48:00.000Z",
    actor: { type: "user", address: "GDQ4...X4KJ", displayName: "Uthaimin" },
    summary: "Session ended",
  },
];
